FROM ubuntu:14.04
MAINTAINER Mark Borcherding <MarkBorcherding@gmail.com>

# Update apt
RUN apt-get update

# Install all the nice to haves
RUN apt-get --quiet --yes install git vim tmux htop curl wget
