production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitlab_ci_production
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

